services:
  - type: web
    name: speech-to-text-backend
    env: node
    plan: free
    buildCommand: npm install && mkdir -p uploads
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DEEPGRAM_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS
        sync: false
      - key: GOOGLE_CLOUD_PROJECT_ID
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true